# Funções

Na aula de hoje, vamos explorar o seguinte tópico em Python:

1. Funções


### Habilidades a serem desenvolvidas

Ao final da aula o aluno deve:

- Conhecer o conceito de funções e sua importância;
- Saber criar funções em Python para diversos casos;

___

## 1) Funções

Até o momento, já vimos diversas funções em Python.

- Na primeira aula, tivemos contato com a função `print()`, que exibe um texto na tela;

- Depois, aprendemos sobre a função `input()`, que serve pra capturar algo que o usuário digita;

- Em seguida, vimos algumas funções aplicada à listas, como a `sorted()`, para ordenar uma lista;

In [ ]:
#Usando a função print
print('Boa aula a todos!')

In [ ]:
#Usando a função input
input('Digite o teu nome: ')

In [ ]:
#Usando a função max
lista = [1,4,10,-5,6,200,5,311,5,2,56,63]
max(lista)

In [ ]:
#Usando a função sorted
lista = [1,4,10,-5,6,200,5,311,5,2,56,63]
sorted(lista)


# Use case real
Agora, imagine que você está desenvolvendo um script para processar transações em um sistema bancário. Os registros das transações estão armazenados no banco de dados, contendo informações sobre clientes, valores das transações, datas e tipos de operações (depósito, saque, transferência). Sua tarefa é:

a. extrair dados pessoais e cadastrais do usuario

b. extrair relatorio de transações do ultimo mes

c. extrair balanço financeiro da conta no ano atual


1. Esse processo vai ser usado no website e no app do banco e deveria ser utilizada sempre que o usuario pedir suas próprias informações. Como o que você faria para tornar esse processo flexivel para cada usuario? 

2. Alguns meses depois, o gerente do Rio das Ostras,RJ precisava obter todas as transações de cartão de crédito realizadas no período da madrugada durante o último mês dos clientes do banco desta região. No programa que você montou o ponto 2 (relatorio de transações do ultimo mes) já extrai todas as transações, como data, horario e tipo de transação. Como você faria para ajudar o gerente?

---
A intuição sobre funções, então, já nos é familiar:

Uma função é um objeto utilizado para **fazer determinadas ações**.

Podemos ver uma função como uma "caixinha" que muitas vezes pega uma **entrada** (o argumento), faz algum **processamento**, e então **retorna uma saída** (o output)

<img src="https://s3.amazonaws.com/illustrativemathematics/images/000/000/782/medium/Task_1_8c7a6a9a2e1421586c40f125bd783de3.jpg?1335065782" width=300>


<img src="https://1.bp.blogspot.com/_MhOt9n2UJbM/TC6emeqHdqI/AAAAAAAAAiQ/1brsWuWvOC0/s1600/function-machine.png" width=300>

Aprenderemos agora como criar **nossas próprias funções** em Python!

## Estrutura da função:

A estrutura de **definição de uma função** é dada por:

```python
def nomeDaFuncao(param1, param2, ...):
    """escrever como funciona a tua função"""
    
    processamento ou instrucoes

    return saida
```

Há 5 elementos fundamentais para a criação de novas funções em Python:

- Primeiramente, usamos `def` para deixar claro que estamos **definindo** uma função;
- Depois, damos um **nome** para nossa função;
- Em parênteses, falamos quais serão os **parâmetros** da função -- esses são os inputs (opcional)
    - Uma função pode conter parâmetros com ou sem valores padrão;
- Depois, explicitamos qual é o **processamento** feito pela função;
- Ao fim, dizemos o que a função irá **retornar** -- esses são os outputs (opcional)

Sempre que quisermos **executar** uma função, basta **chamá-la**, dando os argumentos desejados!

`nome_da_funcao(args)`

* __Uma função sem argumentos e sem return__

**sem argumentos**: Uma função sem agumentos executa alguma ação que não precisa de informação adicional para ser executada.

**sem return**: Esta função não retorna nenhuma VARIÁVEL! (mas pode retornar prints, como veremos no exemplo abaixo)

Vamos para um caso de apenas imprime algo na tela, mas sempre o mesmo texto!

In [1]:
# criar uma função que sempre escreve na tela "estou muito satisfeito com o teu desempenho"
def puxar_o_saco():
    print("Estou muito satisfeito com o teu desempenho")

__Chamando a função__

In [2]:
puxar_o_saco()

Estou muito satisfeito com o teu desempenho

* __Uma função com argumento, mas sem return__

Neste caso, a função agora recebe parâmetros para seus argumentos e eles são utilizados para definir o comportamento da função.

In [11]:
# Refazer a funcao anterior, pedindo o nome do colaborador e
# informar se o nome vai ser inserido no começo ou no fim da frase.
def puxar_o_saco_de_alguem(nome, colocar_nome_no_final:bool):
    if colocar_nome_no_final:
        print(f"Estou muito satisfeito com o teu desempenho, {nome}.")
    else:
        print(f"{nome}, estou muito satisfeito com o teu desempenho.")

In [14]:
puxar_o_saco_de_alguem(colocar_nome_no_final=True , nome='EU')

Estou muito satisfeito com o teu desempenho, EU.

Posso mudar a ordem dos argumentos, mas pra isso devo explicitar exatamente quais são os valores que estou passando para quais argumentos!

In [ ]:
puxar_o_saco_de_alguem(colocar_nome_no_final=False, nome='Rodrigo')

__Mas e o return?__


Todas as funções acima de fato fazem alguma operação, mas nós não conseguimos **acessar** o resultado das operações! 

Um exemplo mais claro: uma função que calcula a soma de dois números:

In [ ]:
# criar uma funcao que soma dois numeros
def somar_dois_numeros(num1, num2):
    soma = num1+num2
    print(soma)

In [ ]:
somar_dois_numeros(10,3)

Note que a função calcula a soma dos números, mas apenas exibe este resultado com o print! 

**A variável "soma" é uma variável que existe apenas no interior da função!!**

In [ ]:
# tentar pegar a variavel de dentro da funcao
soma

Para acessar o resultado, precisamos explicitar qual o resultado que queremos retornar!

In [ ]:
# criar uma funcao que soma dois numeros e retorne o resultado
def somar_dois_numeros(num1, num2):
    soma = num1+num2
    return soma

In [ ]:
somar_dois_numeros(10,3)

Se quisermos armazenar o valor da soma, podemos **retornar** o valor desta variável!<br>
Daí, basta armazenar o resultado retornado em uma variável, **como fazíamos com o input()!**

In [ ]:
# armazenar em `resultado`
resultado = somar_dois_numeros(10,3)

In [ ]:
resultado

**OBS.:** apenas o **valor** da variável é retornado, não o nome dela!! Fora da função, o nome de variável "soma" ainda continua não existindo!!

In [ ]:
soma

Um outro exemplo:

-----
### Hands-on

In [ ]:
# criar funcao que retorna cumprimento de acordo com a hora do dia
# e o nome da pessoa, em forma de texto.
# dica: use f-strings para criar o texto a ser retornado

In [ ]:
# show case

Vamos elaborar um pouco mais?

Que tal fazermos uma função calculadora?

In [ ]:
#func
#Operações: +, -, *, /
# retorna o resultado da operação
# Não esqueça da regra da divisao! Se o usuario a quebrar, mostre uma mensagem e retorne nada.

In [ ]:
# show case

Também é possível utilizar a função calculadora para definir uma função que calcula a média entre dois números:

In [ ]:
# criar uma funcao que utliza a funcao criada anteriormente
def media_dois_numeros(num1,num2):
    # media = soma de n items / n
    media = calculadora(num1, num2, '+')/2
    #retornar o valor
    return media

## Documentação

Muitas vezes temos que trabalhar ou criar funções tão complexas que precisamos de alguma ajuda para entender como funciona a funcao. Por isso, criamos a documentação que ajuda você e outros possíveis usuários ou interessados a entender como funciona uma determinada função.

Por exemplo: vamos ver a documentação da função `print` (basta procurar "Documentation [nome da funcao]" na internet)`:

> <b>print(*objects, sep=' ', end='\n', file=None, flush=False)</b>
<br><br>Print objects to the text stream file, separated by sep and followed by end. sep, end, file, and flush, if present, must be given as keyword arguments.<br><br> All non-keyword arguments are converted to strings like str() does and written to the stream, separated by sep and followed by end. Both sep and end must be strings; they can also be None, which means to use the default values. If no objects are given, print() will just write end. <br><br>The file argument must be an object with a write(string) method; if it is not present or None, sys.stdout will be used. Since printed arguments are converted to text strings, print() cannot be used with binary mode file objects. For these, use file.write(...) instead.<br> <br>Output buffering is usually determined by file. However, if flush is true, the stream is forcibly flushed.<br><br>Changed in version 3.3: Added the flush keyword argument.

Notem que a documentação geralmente está em inglês, ou seja, o inglês é super importante para crescer na área de programação/tecnologia.

Outro ponto a destacar são os parâmetros da função. Neste caso temos 5 parâmetros: `objects`, `sep`, `end`, `file`, `flush`. Como utilizar cada um deles está escrito na documentação.

Além disso, todos os argumentos, exceto o objects, já possuem um valor, que serão os argumentos padrão. Por exemplo, se o usuario chamar a função e não passar nenhum valor explicitamente para o parâmetro `end`, ele entende que este parâmetro vai receber implicitamente o valor '\n', como descrito na função.

Ou seja, os dois comandos fazem a mesma coisa (por que os argumentos já são os valores padrão):

``` python
print('mensagem a ser mostrada', sep=' ', end='\n')
```

ou

``` python
print('mensagem a ser mostrada')
```

# 🎯 Pandas - dados tabulares 🎯<br>


Na aula de hoje veremos com trabalhar com dados tabulares em alto nível, usando a biblioteca [pandas](https://pandas.pydata.org/).

O [Pandas](https://pandas.pydata.org/) é uma das bibliotecas mais usadas em **ciência de dados**.

Esta biblioteca, construída a partir do Numpy, possibilita a estruturação e manipulação de dados de maneira simples e eficiente.

Como os dados são a matéria prima de todo projeto de Data Science, manipulá-los é fundamental! Por isso, utilizaremos o Pandas em quase todas as aulas daqui pra frente!

____
[Guia do pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)

____
Nesta primeira aula, avaliaremos:
- O que são Séries e DataFrames;
- Alguns dos principais métodos para operar com Séries;
- Leitura e gravação de conjuntos de dados com pandas.

____
Até então trabalhamos em análises de dados utilizando listas, dicionários, etc...
Mas pensando em observar dados de tabelas, qual a primeira ferramenta que vem a mente?

Em que situações utilizamos esta ferramenta? E quais suas desvantagens em relação a visualização e manipulação de dados?

# Instalando e importando o Pandas

Primeiro passo para utilizarmos o Pandas (package de manipulação de dados do python). Escreva o comando abaixo no terminal associado ao enviroment do python que estás a usar:

``` sh
pip install pandas
```
<br>
Em seguida, rodamos o comando abaixo no notebook para importar o pandas 

```python
import pandas
```

Caso a etapa anterior não tenha dado certo, surgirá um erro ao importar.

In [15]:
#importar o pandas com alias pd
import pandas as pd

# Séries

Antes de falarmos das potencialidades do *Pandas*, precisamos falar das suas estruturas básicas.

O objeto fundamental do Pandas são as **Series**. As Series são as **colunas das tabelas** (que veremos mais a frente), e por baixo dos panos, os dados ficam armazenados como numpy arrays!

A diferença é que a série possui um **índice associado as linhas**, permitindo o acesso aos conteúdos dessa estrutura por ele, como um dicionário.

Além disso, as séries têm métodos específicos que serão super úteis para nossas análises e manipulações de dados.

## Gerando uma Series
Podemos criar uma série **a partir de uma lista**, usando a função do pandas `pd.Series()`:

In [17]:
#Criando uma lista
lista = [4,6,3,7,25]
lista
# Série a partir de uma lista
# os índices das linhas são automaticamente definidos
serie = pd.Series(lista)

In [19]:
serie

0     4
1     6
2     3
3     7
4    25
dtype: int64

Os números à esquerda são os **índices** da série, e, aqueles à direita, são seus **valores**. Podemos também acessá-los separadamente.

In [24]:
# valores
serie.values

array([ 4,  6,  3,  7, 25], dtype=int64)

In [25]:
# índices
serie.index

RangeIndex(start=0, stop=5, step=1)

A obtenção de itens de uma Series é muito similar à maneira de como fazemos com dicionarios:

In [31]:
serie.items()

Também podemos realizar slicing nas Series, tal como fazemos nas listas.

## Extra: Operações com séries

Como são gerados como numpy arrays, de modo semelhante, operações com séries são realizadas elemento a elemento. E assim podemos somar, multiplicar, realizar qualquer cálculo com as Series.

In [34]:
# Criando duas Series de listas de mesmo tamanho
series1 = pd.Series(range(1,10))
series2 = pd.Series([0,1,100]*3)

In [37]:
# Operações aritméticas básicas funcionam elemento a elemento
# soma
series1+5

0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
dtype: int64

In [38]:
# soma de series
series1+series2

0      1
1      3
2    103
3      4
4      6
5    106
6      7
7      9
8    109
dtype: int64

In [ ]:
# multiplicacao
serie*5

In [ ]:
# multiplicacao de series
series1 * series2

In [39]:
# Condicionais / verificaçoes
# numeros pares
series1 % 2 == 0

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7     True
8    False
dtype: bool

In [ ]:
# numeros maiores que 10
series2 > 10

E com dados de formatos diferentes?

In [42]:
s_texto = pd.Series(['a','b','c'])
s_numero = pd.Series([1,2,3])

O que acontecia com strings mutiplicadas por números inteiros mesmo?

In [40]:
# Com strings
print('a'*1)
print('b'*2)
print('c'*3)

a
bb
ccc

O mesmo efeito acontece entre a multiplicação de series entre strings e números

In [43]:
# Mesmo efeito para as séries
s_texto*s_numero

0      a
1     bb
2    ccc
dtype: object

# DataFrame

Agora que conhecemos as séries, vamos partir pro objeto do Pandas que mais utilizaremos: o **DataFrame**. <br>
Como veremos a seguir, o DataFrame é uma estrutura que se assemalha a uma **tabela** do excel. <br>

Estruturalmente, o DataFrame nada mais é que um **conjunto de Series**, uma para cada coluna (e, claro, com mesmo índice, que irão indexar as linhas).
Veremos depois como **ler um dataframe a partir de um arquivo** (que é provavelmente a forma mais comum).

Há muitas formas de construir um DataFrame do zero. Todas elas fazem uso da função **pd.DataFrame()**, como veremos a seguir. Se quisermos especificar os índices de linha, o nome das colunas, e os dados, podemos passá-los separadamente.

**Obs.:** As colunas dos DataFrames são Series. Assim, tudo que vimos para as séries se aplica para cada coluna do DataFrame!

In [44]:
# Gerando uma matriz (5,3) de números inteiros
nrows = 5
ncols = 3
matriz = [[item*r for item in range(1,ncols+1)] for r in range(1,nrows+1)]
matriz

[[1, 2, 3], [2, 4, 6], [3, 6, 9], [4, 8, 12], [5, 10, 15]]

In [46]:
#Transformando essa matriz em um DF
df = pd.DataFrame(matriz)
df

   0   1   2
0  1   2   3
1  2   4   6
2  3   6   9
3  4   8  12
4  5  10  15

In [47]:
# Conseguimos definir nomes pros índices e colunas
df = pd.DataFrame(matriz,
                  index = ['aluno1','aluno2','aluno3','aluno4','aluno5'],
                  columns=['id','nota','aulas_presente'])

In [48]:
df

        id  nota  aulas_presente
aluno1   1     2               3
aluno2   2     4               6
aluno3   3     6               9
aluno4   4     8              12
aluno5   5    10              15

## Acessando posições do dataframe

- .loc[]: acessamos os rótulos com os **nomes** das linhas e colunas;
- .iloc[]: acessamos os índices numéricos das linhas e colunas.

In [56]:
# acessar a nota do aluno4
df.loc['aluno4','nota']

8

In [58]:
# o mesmo acima usando iloc
df.iloc[3,1]

8

Podemos selecionar uma coluna específica ou colunas específicas do DF.

In [61]:
# uma col
df['nota']

aluno1     2
aluno2     4
aluno3     6
aluno4     8
aluno5    10
Name: nota, dtype: int64

In [63]:
#multiplas cols
df[['nota','id']]

        nota  id
aluno1     2   1
aluno2     4   2
aluno3     6   3
aluno4     8   4
aluno5    10   5

In [70]:
# slicing de linhas e cols
df.loc['aluno2':'aluno4']
df.loc[:,'id':'nota']

        id  nota
aluno1   1     2
aluno2   2     4
aluno3   3     6
aluno4   4     8
aluno5   5    10

In [ ]:
# utilizando o iloc

Analogamente, podemos usar o `iloc` para obter os mesmos dados utilizando os índices (fica como tarefa para você demonstrar isto).

As colunas do dataframe são séries. Assim, tudo que vimos para as séries, se estende individualmente para cada coluna!

# Outros métodos para DataFrames

Como uma coluna de um DF é uma Série, a maioria dos métodos que veremos para DataFrames também são aplicados as Series.

Veremos 2 que trazem informações sobre nosso DF: `info`() e `dtypes` e `shape`.

## shape

In [74]:
df.shape

(5, 3)

## info()

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, aluno1 to aluno5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              5 non-null      int64
 1   nota            5 non-null      int64
 2   aulas_presente  5 non-null      int64
dtypes: int64(3)
memory usage: 332.0+ bytes

também podemos acessar os tipos de dados por coluna separadamente utilizando o `dtypes`

In [78]:
df.dtypes

id                int64
nota              int64
aulas_presente    int64
dtype: object

Podemos ainda, trocar o tipo de alguma variável. Exemplo, trocar uma coluna de inteiro para decimal:

In [79]:
df['nota'] = df['nota'].astype(float)
df

        id  nota  aulas_presente
aluno1   1   2.0               3
aluno2   2   4.0               6
aluno3   3   6.0               9
aluno4   4   8.0              12
aluno5   5  10.0              15

## head()

In [81]:
#Ver as primeiras 5 linhas
df.head(2)

        id  nota  aulas_presente
aluno1   1   2.0               3
aluno2   2   4.0               6

In [ ]:
# Ver as primeiras 7 linhas

## tail()

In [82]:
#Ver as últimas 5 linhas (análogo ao `head` pode-se alterar a quantidade de linhas)
df.tail()

        id  nota  aulas_presente
aluno1   1   2.0               3
aluno2   2   4.0               6
aluno3   3   6.0               9
aluno4   4   8.0              12
aluno5   5  10.0              15

# Máscara booleana

A máscara booleana é uma técnica no Pandas para filtrar dados com base em condições. Vamos aprender como criar e usar máscaras booleanas para selecionar partes específicas dos dados.<br>
Utilizaremos ela também em outras funções, como `loc[]`.

Imagine que queiramos filtrar somente os alunos com `nota` maiores que 5 no DataFrame. 

Primeiro aplicamos uma condição na coluna (Series) em que traz somente `True` ou `False`:

In [85]:
# notas maiores que 5
mask = df['nota'] > 5

Em seguida aplicamos este resultado no DataFrame. Isto significa que só queremos exibir as linhas em que a condição é satisfeita (também podemos aplicar no `loc` a mesma condição):

In [96]:
df[mask]
df[(df['nota']>5) & (df['aulas_presente']>10)]

        id  nota  aulas_presente
aluno4   4   8.0              12
aluno5   5  10.0              15

Caso o filtro aplicado não seja tão complexo, não há problema escrever a condição da máscara booleana inteira.

```python
df[df['nota'] > 5]
```

# Importando dados

A forma mais comum de se construir um dataframe é a partir da **leitura de um arquivo** (.csv, .xls, .xlsx, .ods, .txt, .json, etc.)

O pandas é capaz de ler todos esses formatos, com funções específicas!

## Arquivos CSV

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

Vamos ler os dados do avaliaçãoes de restaurantes de New York do arquivo `Cuisine_ratings.csv` na pasta `data` e criar um DataFrame:

In [97]:
#import
import pandas as pd

# Lendo um arquivo CSV e criando um DataFrame
df_rating = pd.read_csv('data/Cuisine_rating.csv')

In [101]:
df_rating

,User ID,Area code,Location,Gender,YOB,Marital Status,Activity,Budget,Cuisines,Alcohol,Smoker,Food Rating,Service Rating,Overall Rating,Often A S
0,1,153,"Upper East Side,NY",Female,2006,Single,Professional,3,Japanese,Never,Never,5,4,4.5,No
1,2,123,"St. George,NY",Female,1991,Married,Student,3,Indian,Never,Socially,1,1,1.0,No
2,3,122,"Upper West Side,NY",Male,1977,Single,Student,5,Seafood,Often,Often,5,5,5.0,Yes
3,4,153,"Upper East Side,NY",Female,1956,Married,Professional,5,Japanese,Never,Socially,3,1,2.0,No
4,5,129,"Central Park,NY",Male,1997,Single,Student,4,Filipino,Socially,Never,2,4,3.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,175,"St. George,NY",Female,1982,Single,Professional,4,French,Never,Socially,1,2,1.5,No
196,197,170,"Upper West Side,NY",Female,2000,Married,Student,4,Chinese,Never,Often,1,2,1.5,No
197,198,160,"St. George,NY",Female,2006,Single,Professional,5,Japanese,Never,Often,5,2,3.5,No
198,199,130,"St. George,NY",Male,2002,Married,Student,3,Filipino,Never,Socially,3,2,2.5,No
199,200,140,"Upper East Side,NY",Male,2005,Married,Student,4,French,Never,Never,3,2,2.5,No

Podemos aplicar todos os métodos vistos anteriormente para analisar o dataset carregado acima.

## EXTRA: Planilha Excel (XLS ou XLSX)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

Vamos criar um dataframe com os dados da Selic vindos de uma planilha de excel `selic.xlsx` na pasta `data`

In [ ]:
#pip install openpyxl -- pode ser necessário instalar openpyxl, mas tente rodar o exemplo abaixo primeiro

In [ ]:
df_selic = pd.read_excel('./data/selic.xlsx')

In [ ]:
df_selic

**Leitura com seleção de planilha**

Podemos também carregar somente uma determinada sheet utilizando o param `sheet_name` na função `read_excel`

In [ ]:
df_titanic = pd.read_excel('./data/titanic.xlsx',sheet_name='Sheet1')

In [ ]:
df_titanic

___
# Hands-on

Neste Hands-on vamos realizar alguns passos do EDA no step 0 `Reconhecimento dos dados` e alguns insights também.

1. Carregar os dados de pedidos de empréstimos pessoais `Projectdata_Bank_Personal_Loan_Modelling.csv`

2. Ver os primeiros 7 dados do topo e do fim do dataset.

3. Exibir todas as possíveis informações basicas do dataset (tamanho, tipos de dados, ...)

4. Filtre o dataframe entre clientes que possuem e não possuem CDB na column `CD Account` com as categorias `1` e `0`, respectivamente.<br>
Salve os filtros (máscaras booleanas) em variáveis diferentes.

5. Filtre novamente o DataFrame, porém agora entre clientes que são solteiros e que possuem mais de um mebro na família (analise o dataset para descobrir como fazê-lo).<br>
Salve os filtros (máscaras booleanas) em variáveis diferentes.

6. Realize o mesmo que no exer anterior, porém somente com a Educação dos clientes.
Salve o filtro (máscaras booleanas) em uma variável.

7. Utilizando os filtros salvos em variaveis nos exer 4,5 e 6, filtre o dataset para mostrar somente os clientes profissionais que não possuem CDB e que são solteiros. Não é preciso salvar o filtro aplicado.

8. Sobre o dataset filtrado, quantos clientes utilizam serviços digitais (online)?

9. Filtre sobre o resultado anterior somente os clientes que aceitaram o empréstimo oferecido. Quantos clientes foram filtrados em relação ao total? O que se pode notar com o resultado obtido sobre os tipos de cliente?

# PANDAS - Processamento de dados
[Guia do pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)
____

Dúvidas?
* Romero Carvalho: romerofcarvalho (discord)
* Allan Suzuki: allansuzuki (discord)

In [ ]:
#imports 
import pandas as pd
import numpy as np

def pegar_alguem():
    text_alunos = """
a1,
a2,
a3,
a4
"""
    alunos = text_alunos.split('\n\n')
    return np.random.choice(alunos,1)[0]

# Topicos
1. [Caso prático](#caso-pratico)
2. [O que vamos aprender?](#o-que-vamos-aprender)
3. [Exercícios](#exer)

Caso prático - 10m  (5min em cada)
<br>Concat + merge      (1h)
<br>Pivot + melt        (1h)
<br>Exercícios          (1h)

# Caso prático <div id="caso-pratico">

## Caso 1

Vamos considerar uma situação com dados relacionados a clientes, médicos, consultas e procedimentos médicos, cada um armazenado em tabelas separadas. Durante a análise dos dados de clientes e médicos, notamos que algumas informações não estão atualizadas. **O desafio** é que extrair todos os dados novamente levaria bastante tempo de processamento.

<!-- `imagem aqui para ilustrar a falta de dados dessas tabelas` -->

O que você faria para solucionar este problema?

<!--- tempo de espera para ver como resolver --->

**SOLUÇÃO**:<!-- Diante dessa questão, a equipe decidiu adotar uma abordagem mais prática: em vez de recarregar todos os dados, a ideia é identificar **apenas** as informações que estão faltando e adicioná-las aos dados desatualizados. -->

## Caso 2

Durante uma reunião estratégica voltada para a identificação de oportunidades e aprimoramentos com os clientes, Alessandra apresentou à equipe de estratégia os resultados de uma enquete pública realizada no site da Unimed e na rua. Esses resultados incluíam dados demográficos (endereço, cidade, estado) e socioeconômicos (renda familiar, tamanho da família, qualidade de vida), bem como a opinião dos participantes em relação à Unimed de 1 a 5, variando de muito ruim a muito bom. No entanto, a equipe enfrentava dificuldades em compreender os insights dos resultados da enquete devido à forma como os dados estavam organizados, já que cada resposta ocupava uma linha e não conseguia visualizar o todo.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>id_pesquisa</th>
      <th>nome</th>
      <th>idade</th>
      <th>renda</th>
      <th>satisfacao</th>
      <th>recomendacao</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>dados omitidos</td>
      <td>40</td>
      <td>6</td>
      <td>7</td>
      <td>3</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2</td>
      <td>dados omitidos</td>
      <td>56</td>
      <td>7</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2</th>
      <td>3</td>
      <td>dados omitidos</td>
      <td>32</td>
      <td>4</td>
      <td>5</td>
      <td>3</td>
    </tr>
    <tr>
      <th>3</th>
      <td>4</td>
      <td>dados omitidos</td>
      <td>16</td>
      <td>7</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5</td>
      <td>dados omitidos</td>
      <td>72</td>
      <td>9</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>5</th>
      <td>6</td>
      <td>dados omitidos</td>
      <td>48</td>
      <td>2</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>6</th>
      <td>7</td>
      <td>dados omitidos</td>
      <td>48</td>
      <td>3</td>
      <td>5</td>
      <td>2</td>
    </tr>
    <tr>
      <th>7</th>
      <td>8</td>
      <td>dados omitidos</td>
      <td>40</td>
      <td>5</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <th>8</th>
      <td>9</td>
      <td>dados omitidos</td>
      <td>56</td>
      <td>3</td>
      <td>2</td>
      <td>2</td>
    </tr>
    <tr>
      <th>9</th>
      <td>10</td>
      <td>dados omitidos</td>
      <td>32</td>
      <td>8</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>10</th>
      <td>11</td>
      <td>dados omitidos</td>
      <td>80</td>
      <td>10</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <th>11</th>
      <td>12</td>
      <td>dados omitidos</td>
      <td>48</td>
      <td>8</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>12</th>
      <td>13</td>
      <td>dados omitidos</td>
      <td>32</td>
      <td>8</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>13</th>
      <td>14</td>
      <td>dados omitidos</td>
      <td>16</td>
      <td>9</td>
      <td>5</td>
      <td>1</td>
    </tr>
    <tr>
      <th>14</th>
      <td>15</td>
      <td>dados omitidos</td>
      <td>56</td>
      <td>4</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>15</th>
      <td>16</td>
      <td>dados omitidos</td>
      <td>24</td>
      <td>5</td>
      <td>3</td>
      <td>1</td>
    </tr>
    <tr>
      <th>16</th>
      <td>17</td>
      <td>dados omitidos</td>
      <td>32</td>
      <td>5</td>
      <td>6</td>
      <td>2</td>
    </tr>
    <tr>
      <th>17</th>
      <td>18</td>
      <td>dados omitidos</td>
      <td>16</td>
      <td>8</td>
      <td>5</td>
      <td>3</td>
    </tr>
    <tr>
      <th>18</th>
      <td>19</td>
      <td>dados omitidos</td>
      <td>80</td>
      <td>7</td>
      <td>2</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19</th>
      <td>20</td>
      <td>dados omitidos</td>
      <td>72</td>
      <td>9</td>
      <td>4</td>
      <td>3</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21</td>
      <td>dados omitidos</td>
      <td>24</td>
      <td>8</td>
      <td>6</td>
      <td>3</td>
    </tr>
</table>

O que você faria para reestruturar os dados e gerar insights estratégicos mais rapidamente?

**SOLUÇÃO**:<!-- Uma solução eficaz seria reorganizar os dados, pivotando os dados para categorizar por classes socioeconômicas e regiões demográficas. Essa abordagem permitiria visualizar os resultados agregados da opinião pública de maneira mais clara e compreensível. Ao adotar uma perspectiva semelhante à funcionalidade Pivot Table do Excel, a equipe estaria mais familiarizada e apta a extrair insights significativos de maneira mais rápida e eficiente. -->

# O que vamos aprender? <div id="o-que-vamos-aprender">

* [Concat](#Concat)
* [Merge](#Merge)
* [Groupby](#groupby)
* [Pivot](#Pivot)
* [Melt](#Melt)

## Até onde chegamos

&ensp;<img src="./img/recap_lecture.png" alt="create_notebook" width="400"/>

Aprendemos a trabalhar com diversas funções para:
1. carregar dados vindo de fontes externas;
2. localizar dados específicos;
3. realizar cálculos;
4. salvar os dados em outro tipo de arquivo.

Perceba que para aplicar cada uma dessas funções, somente é necessário UM único dataframe.

## Até onde vamos chegar (com este módulo)

&ensp;<img src="./img/lecture_target.png" alt="lecture_target" width="400"/>

Neste módulo vamos conseguir realizar uniões/manipulações entre duas ou mais dataframes ou estruturar um dataframe para outra forma (tal como os dois casos que vimos no começo do módulo).

## Concat 
Source: Documentation [(+info)](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)

As vezes, é preciso um novo conjunto de dados a partir de união de outros dados/tabelas. 

No caso, quando queremos concatenar/unir/empilhar dados num determinado eixo (lembra-se do que significa eixo em DataFrames?), utilizamos a função **pandas.concat** (semelhante a operação UNION do SQL):

>pandas.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=None)
<br>&ensp;&ensp;&ensp;&ensp;Concatenate pandas objects along a particular axis.
<br><br>&ensp;&ensp;&ensp;&ensp;Allows optional set logic along the other axes
<br><br>&ensp;&ensp;&ensp;&ensp;Can also add a layer of hierarchical indexing on the concatenation axis, which may be useful if the labels are the same (or overlapping) on the passed axis number.

É possível combinar duas séries:

In [116]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])

pd.concat([s1,s2])

0    a
1    b
0    c
1    d
dtype: object

Bem como combinar dois DataFrames com as mesmas colunas:

In [117]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])
pd.concat([df1,df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Porém, combinar dois DataFrames que possuem diferentes colunas retorna valores **NaN** (o que é isto mesmo?):

In [118]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']], columns=['letter', 'number', 'animal']) # one more column
pd.concat([df1,df2,df3])

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    NaN
1      d       4    NaN
0      c       3    cat
1      d       4    dog

É possível resetar os índices com o argumento `ignore_index=True`, quando os índices originais não são importantes.

In [120]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']], columns=['letter', 'number', 'animal']) # one more column
pd.concat([df1, df2, df3], ignore_index=True)

  letter  number animal
0      a       1    NaN
1      b       2    NaN
2      c       3    NaN
3      d       4    NaN
4      c       3    cat
5      d       4    dog

Também é possível combinar os DataFrames pelos índices (ao invés das colunas) utilizando o argumento `axis=1`

In [123]:
df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']], columns=['animal', 'name']) # new columns
pd.concat([df1,df4], axis=1)

  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

-----
### Hands-on

1. Você tem uma tarefa de criar um DataFrame no seguinte formato:
<br>
<br>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>Name</th>
      <th>Class</th>
      <th>InsuranceTotalSpent</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Ana</td>
      <td>Enterprise</td>
      <td>1200</td>
    </tr>
    <tr>
      <td>Lucas</td>
      <td>Personal</td>
      <td>900</td>
    </tr>
    <tr>
      <td>Isabella</td>
      <td>Enterprise</td>
      <td>1500</td>
    </tr>
    <tr>
      <td>Thiago</td>
      <td>Elite</td>
      <td>800</td>
    </tr>
    <tr>
      <td>Gabriela</td>
      <td>Personal</td>
      <td>1100</td>
    </tr>
  </tbody>
</table>
<br>

Em seguida o teu par te mandou o restante dos dados e pediu para uní-los enquanto ele puxava os dados complementares. Os dados adicionais estão no arquivo `dados_adicionais.csv`.

In [136]:
display(df)

        id  nota  aulas_presente
aluno1   1   2.0               3
aluno2   2   4.0               6
aluno3   3   6.0               9
aluno4   4   8.0              12
aluno5   5  10.0              15

In [143]:
# criar um df com base nos dados acima
df = pd.DataFrame(
    [
        ["Ana","Enterprise",1200],
        ['Lucas','Personal',900],
        ['Isabella','Enterprise',1500],
        ['Thiago','Elite',800],
        ['Gabriela','Personal',1100]
    ],
    columns= ['Name','Class','InsuranceTotalSpent']
)

# carregar csv
df1 = pd.read_csv('data/dados_adicionais.csv')

# union dois dfs
df_final = pd.concat([df,df1])

2. Após a primeira entrega dos dados, um novo cliente apareceu nas bases de dados e teu superior pediu prioridade para incluir esse estimado cliente nos teus dados. Você se lembrou do 1o caso prático desta aula e pediu os dados do novo cliente para incluí-lo:
> Name: Romero F Carvalho
<br> Class: Premium
<br> InsuranceTotalSpent: 90000

In [160]:
nova_linha = pd.DataFrame(['Romero','Premium',90000], index=['Name','Class','InsuranceTotalSpent'])
pd.concat([df_final,nova_linha.T])

       Name       Class InsuranceTotalSpent
0       Ana  Enterprise                1200
1     Lucas    Personal                 900
2  Isabella  Enterprise                1500
3    Thiago       Elite                 800
4  Gabriela    Personal                1100
0   Mariana    Personal                 950
1     Pedro  Enterprise                1300
2    Camila       Elite                 750
0    Romero     Premium               90000

## Merge
Source: Documentation [(+info)](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

Muitas vezes queremos buscar dados adicionais de outro DataFrame que possuem algum interligação / relacionamento entre si. 

Neste caso, utilizamos a função **pandas.merge** (semelhante a operação JOIN do SQL):

<img src="https://community.qlik.com/legacyfs/online/87693_all-joins.png" width=450>
<br><br>

>DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=None, indicator=False, validate=None)
<br><br>&ensp;&ensp;&ensp;&ensp;Merge DataFrame or named Series objects with a database-style join.
<br><br>&ensp;&ensp;&ensp;&ensp;A named Series object is treated as a DataFrame with a single named column.

Podemos juntar as informações de dois DataFrames que se relacionam por chaves (keys) comuns entre si:

In [162]:
df_pacientes = pd.DataFrame({'paciente_id': [1, 2, 3], 'idade': [25, 35, 40]})
df_exames = pd.DataFrame({'paciente_id': [1, 2, 4], 'resultado': ['Normal', 'Elevado', 'Ausente']})
df_pacientes.merge(df_exames, on='paciente_id')

   paciente_id  idade resultado
0            1     25    Normal
1            2     35   Elevado

Se quisermos mudar o tipo da união (qual é a união padrão?), utilizamos o parâmetro `how` que aceita os seguintes valores: 
> how : {‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross’}

In [163]:
df_pacientes = pd.DataFrame({'paciente_id': [1, 2, 3], 'idade': [25, 35, 40]})
df_exames = pd.DataFrame({'paciente_id': [1, 2, 4], 'resultado': ['Normal', 'Elevado', 'Ausente']})
df_pacientes.merge(df_exames, on='paciente_id', how='outer')

   paciente_id  idade resultado
0            1   25.0    Normal
1            2   35.0   Elevado
2            3   40.0       NaN
3            4    NaN   Ausente

Note que, no tipo união `outer`, não há um `paciente_id 4` no `df_pacientes`, por isso não temos a idade dele e, por padrão, nos retorna `NaN`, bem como não temos resultados do exame para o `paciente_id 3`.

Caso as colunas-chave não tenham nomes iguais, podemos utilizar os parâmetros `left_on` e `right_on`:

In [164]:
df_pacientes = pd.DataFrame({'paciente_id': [1, 2, 3], 'idade': [25, 35, 40]})
df_exames_outro = pd.DataFrame({'id_pacientes': [1, 2, 4], 'resultado': ['Normal', 'Elevado', 'Ausente']})
df_pacientes.merge(df_exames_outro, left_on='paciente_id',right_on='id_pacientes', how='outer')

   paciente_id  idade  id_pacientes resultado
0          1.0   25.0           1.0    Normal
1          2.0   35.0           2.0   Elevado
2          3.0   40.0           NaN       NaN
3          NaN    NaN           4.0   Ausente

Se houver colunas que têm o mesmo nome e não serão chave, podemos diferenciá-los pelos argumento suffixes=('rsuff','lsuff'):

In [167]:
df_exames = pd.DataFrame({'paciente_id': [1, 2, 4], 'resultado': ['Normal', 'Elevado', 'Ausente']})
df_renovacao_seguro = pd.DataFrame({'paciente_id': [1, 2, 4], 'resultado': ['Aprovado', 'Aprovado', 'Em analise']})
# df_exames.merge(df_renovacao_seguro, on='paciente_id')
df_exames.merge(df_renovacao_seguro, on='paciente_id', suffixes=('_exame','_renovacao'))

   paciente_id resultado_exame resultado_renovacao
0            1          Normal            Aprovado
1            2         Elevado            Aprovado
2            4         Ausente          Em analise

-----
### Hands-on

1. Teu colega da recepcao pediu os dados das consultas realizadas do arquivo `data/merge_handsOn`. Porém, a tabela não parece conter informações relevantes para um usuário comum. Para resolver isto, uma prática muito comum no SQL é unir tabelas para ter todas as informações em texto, ao invés de códigos.

<br> Na pasta `data/merge_handsOn` temos 3 csvs que trazem dados dos pacientes, medicos e hospitais. Utilize o merge para identificar todas as informações referentes as consultas realizadas e entregar dados legíveis para o teu colega.

## Groupby <div id="groupby">
Source: Documentation [(+info)](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)

Muitas vezes, estaremos interessados em aplicar técnicas de agrupamentos de dados, tal como somas ou contagens, aplicados a dados que pertençam ao mesmo grupo. 
<br><br>Por exemplo: quantas pessoas de <u>cada</u> **departamento** trabalham na empresa XPTO?

 Para isso, utilizaremos funções como  **DataFrame.groupby()**, semelhante a operação GROUP BY do SQL, e a função [DataFrameGroupBy.agg()](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.core.groupby.DataFrameGroupBy.agg.html), semelhante as opeações de agregamento no SELECT do SQL.

>DataFrame.groupby(by=None, axis=_NoDefault.no_default, level=None, as_index=True, sort=True, group_keys=True, observed=_NoDefault.no_default, dropna=True)
<br><br>&ensp;&ensp;&ensp;&ensp;Group DataFrame using a mapper or by a Series of columns.
<br><br>&ensp;&ensp;&ensp;&ensp;A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.

Sempre que utilizarmos o groupby, normalmente estamos interessados em agrupar os dados e aplicar uma função de agregamento (ex: max):

In [201]:
df = pd.DataFrame({'animal': ['Falcon', 'Falcon', 'Parrot', 'Parrot'],
                   'speed': [380., 370., 24., 26.]})
df
df.groupby('animal')['speed'].agg(func='max').rename('renomeado')

        renomeado
animal
Falcon      380.0
Parrot       26.0

Note que se não dissermos qual é a coluna a ser aplicada a função agg(), é aplicado a todas as colunas:

In [186]:
df2 = df.copy() #make a copy
df2['height'] = [100, 105, 95, 90]  # add new data
# df2
df2.groupby('animal').agg(func='max')

        speed  height
animal
Falcon  380.0     105
Parrot   26.0      95

É possível também aplicar uma função criada, desde que seja aplicada para o mesmo tipo de objeto resultante do groupby:

In [187]:
def funcao_criada(df_qualquer):
    """
    Funcao que recebe um DataFrame a
    diferença entre o valor max e o min
    """
    df_min = df_qualquer.min()
    df_max = df_qualquer.max()

    return df_max-df_min

# df.groupby('animal').agg(func=)    #não tem ()
df.groupby('animal').agg(func=[max,min,funcao_criada])    #não tem ()

        speed
          max    min funcao_criada
animal
Falcon  380.0  370.0          10.0
Parrot   26.0   24.0           2.0

Nota: Normalmente, após um groupby, temos um objeto do tipo `DataFrameGroupBy`, que é composto por vários DataFrames ou Series.

In [40]:
df_groupby = df.groupby('animal')
print('Tipo da variavel df_groupby:',type(df_groupby))

# get one group from groupby
for obj_dentro_do_groupby in df_groupby:
    print('\nObjeto dentro do groupby:\n',obj_dentro_do_groupby)
    print('\nTipo do objeto dentro do groupby:',type(obj_dentro_do_groupby))
    print('\nTipo do objeto dentro do objeto dentro do groupby:',type(obj_dentro_do_groupby[1]))
    break   # o que acontece se tirar esse`break`?

Tipo da variavel df_groupby: <class 'pandas.core.groupby.generic.DataFrameGroupBy'>

Objeto dentro do groupby:
 ('Falcon',    animal  speed
0  Falcon  380.0
1  Falcon  370.0)

Tipo do objeto dentro do groupby: <class 'tuple'>

Tipo do objeto dentro do objeto dentro do groupby: <class 'pandas.core.frame.DataFrame'>

-----
### Hands-on

Vamos analisar os dados de casos de covid no mundo se encontra no caminho: support_data/covid_country_latest.csv Quantos `confirmed_cases` por dia aconteciam no mundo inteiro? Qual foi o dia com maior quantidade de `confirmed_cases` e `deaths`?

<!-- **Desafio**: Vamos tentar quais foram os top 3 registros por páis com mais `deaths`. Comece primeiro com o dataset inteiro:   -->

## Pivot
Source: Documentation [(+info)](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html)

Muitos usuários estão mais acostumados a olhar tabelas parecidas com as planilhas de MS Excel, comumente utilizando as tabelas dinâmicas (ou *pivot table* em inglês). Para transformar nossos dados em formatos parecidos com este, utilizamos a função DataFrame.pivot()

> DataFrame.pivot(*, columns, index=_NoDefault.no_default, values=_NoDefault.no_default)
<br><br>&ensp;&ensp;&ensp;&ensp;Return reshaped DataFrame organized by given index / column values.
<br><br>&ensp;&ensp;&ensp;&ensp;Reshape data (produce a “pivot” table) based on column values. Uses unique values from specified index / columns to form axes of the resulting DataFrame. This function does not support data aggregation, multiple values will result in a MultiIndex in the columns. See the User Guide for more on reshaping.

Para realzar o pivot, basta dizer qual(is) a(s) columna(s) para os argumentos:
- `index`
- `columns` 
- `values`

<!-- `img de um dataset no pivot` -->

In [188]:
data = {
    'animal': ['Elefante', 'Leão', 'Girafa', 'Tigre', 'Pinguim'],
    'habitat': ['Savana', 'Savana', 'Savana', 'Floresta', 'Polo Sul'],
    'qtd': [10, 15, 8, 12, 20]
}

df_animais_habitat = pd.DataFrame(data)

df_animais_habitat.pivot(index='animal',columns='habitat',values='qtd')

habitat   Floresta  Polo Sul  Savana
animal
Elefante       NaN       NaN    10.0
Girafa         NaN       NaN     8.0
Leão           NaN       NaN    15.0
Pinguim        NaN      20.0     NaN
Tigre         12.0       NaN     NaN

Nota-se que quando não há valores para uma determinada combinação, por padrão retorna (adivinha?) `NaN`.

Caso fosse realizado o mesmo levantamento de antes, mas com novos dados, não seria possível utilizar `pivot()` juntando os dados para ter um resultado somado ao anterior:

In [ ]:
novos_levantamentos = pd.DataFrame({
    'animal': ['Elefante', 'Leão', 'Girafa', 'Tigre', 'Pinguim','Elefante'],
    'habitat': ['Savana', 'Savana', 'Savana', 'Floresta', 'Polo Sul','Floresta'],
    'qtd': [5, 10, 15, 8, 25, 10]  # Quantidades diferentes, ultimo é novo registro
})

# adicionando novos_levantamentos
new_df = pd.concat([df_animais_habitat, novos_levantamentos])   # o que isto faz mesmo?

new_df.pivot(index='animal',columns='habitat',values='qtd')
# uai... pq deu erro?

Isso acontece porque esta função não realiza nenhuma função de agregamento (quais são?) quando temos dados diferentes para a a mesma relação índice-coluna!

Nesse caso, devemos utilizar a função DataFrame.pivot_table() com o argumento `aggfunc` com a função de agregamento que queremos.

No caso anterior, queríamos somar quando houvesse novos levantamentos para o mesmo grupo, certo?

In [ ]:
new_df.pivot_table(index='animal',columns='habitat',values='qtd', aggfunc='sum')

----
### Hands-on

Lembra do **caso prático 2** no ínicio da aula? Vamos simular um dataset para efetuar esta tarefa:

Durante uma reunião estratégica voltada para a identificação de oportunidades e aprimoramentos com os clientes, Alessandra apresentou à equipe de estratégia os resultados de uma enquete pública realizada no site da Unimed e na rua. Esses resultados incluíam dados pessoais: nome, idade, renda (em salarios mínimos);
e resultados da pesquisa: nível de satisfação e recomendação do serviço.

No entanto, a equipe enfrentava dificuldades em compreender os insights dos resultados da enquete devido à forma como os dados estavam organizados, já que cada resposta ocupava uma linha e não conseguia visualizar o todo.

O que você faria para reestruturar os dados e gerar insights estratégicos mais rapidamente?

In [ ]:
def simular_resultados_da_pesquisa(nseed:int=42):
    """
    Criando um DataFrame de pesquisa de satisfação.
    Retorna um pd.DataFrame
    """

    import numpy as np
    np.random.seed(nseed)  # Definindo semente para reprodutibilidade

    # Gerando valores para as colunas
    num_participantes = 1000
    idades = np.arange(16, 81, 8)
    rendas = np.arange(1, 11, 1)
    satisfacao = np.random.randint(1, 8, size=num_participantes)
    recomendacao = np.random.randint(1, 4, size=num_participantes)

    # Criando o DataFrame
    df_pesquisa = pd.DataFrame({
        'id_pesquisa': np.arange(1, num_participantes + 1),
        'nome': ['dados omitidos'] * num_participantes,
        'idade': np.random.choice(idades, size=num_participantes),
        'renda': np.random.choice(rendas, size=num_participantes),
        'satisfacao': satisfacao,
        'recomendacao': recomendacao
    })

    return df_pesquisa

simular_resultados_da_pesquisa().to_html('./support_data/not_use.html')

## Melt

Quando precisamos do oposto ao pivot (unpivot), ou seja, quando alguém nos entrega os dados resultantes de um pivot table feito no MS Excel para ser utilizado em uma análise de dados, utilizamos **DataFrame.melt()**.

>DataFrame.melt(id_vars=None, value_vars=None, var_name=None, value_name='value', col_level=None, ignore_index=True)
<br><br>&ensp;&ensp;&ensp;&ensp;Unpivot a DataFrame from wide to long format, optionally leaving identifiers set.
<br><br>&ensp;&ensp;&ensp;&ensp;This function is useful to reshape a DataFrame into a format where one or more columns are identifier variables (id_vars), while all other columns, considered measured variables (value_vars), are “unpivoted” to the row axis, leaving just two non-identifier columns, ‘variable’ and ‘value’.

Vamos utilizar os dados pivotados da seção anterior:

In [ ]:
# # pivot data
# pivot_data = new_df.pivot_table(index='animal',columns='habitat',values='qtd', aggfunc='sum')

Primeiro, vamos olhar como como é o resultado de um pivot_table()

In [ ]:
# print('columns:', pivot_data.columns.tolist())
# print('index:', pivot_data.index.name)
# display(pivot_data.head())

Meu id_vars (olha os args do melt) ideal são os dados que estão no `index`, que eu não consigo acessar pelos `['']` porque não é uma coluna (olhar e comparar os dados do exemplo na documentação).

In [ ]:
#nao consigo acessar os indices aqui:
# pivot_data['animal'] #erro!

Portanto, uma forma de obter esses dados é fazer com que o índice vire uma coluna do DataFrame:

In [ ]:
# pivot_data.reset_index()['animal']   # faz com que o indice comece do 0, além disso, transforma o indíce anterior em coluna

In [ ]:
# pivot_data.reset_index().melt(id_vars='animal')